import React, { useEffect, useRef, useState } from 'react';

// Atom colors based on CPK coloring convention
const ATOM_COLORS = {
  H: '#ffffff',  // White
  C: '#909090',  // Gray
  N: '#3050f8',  // Blue
  O: '#ff0d0d',  // Red
  P: '#ff8000',  // Orange
  S: '#ffff30',  // Yellow
  Cl: '#1ff01f', // Green
  F: '#90e050',  // Light Green
  Fe: '#e06633', // Orange-red
  Zn: '#7d80b0', // Blue-gray
};

function MoleculeViewer({ moleculeType, simulationResults }) {
  const [error, setError] = useState(false);
  const viewerRef = useRef(null);

  // Predefined molecule structures for demo
  const fallbackMolecules = {
    water: [
      { symbol: 'O', x: 0, y: 0, z: 0 },
      { symbol: 'H', x: 0.76, y: 0.59, z: 0 },
      { symbol: 'H', x: -0.76, y: 0.59, z: 0 }
    ],
    pesticide: [
      { symbol: 'C', x: 0, y: 0, z: 0 },
      { symbol: 'C', x: 1.4, y: 0, z: 0 },
      { symbol: 'N', x: 2.8, y: 0, z: 0 },
      { symbol: 'O', x: 1.4, y: 1.4, z: 0 },
      { symbol: 'Cl', x: 0, y: -1.4, z: 0 },
      { symbol: 'H', x: 2.8, y: 1.4, z: 0 }
    ],
    nutrient: [
      { symbol: 'C', x: 0, y: 0, z: 0 },
      { symbol: 'N', x: 1.4, y: 0, z: 0 },
      { symbol: 'N', x: 2.8, y: 0, z: 0 },
      { symbol: 'O', x: 1.4, y: 1.4, z: 0 },
      { symbol: 'Fe', x: 4.2, y: 0.7, z: 0 }
    ]
  };

  const atoms = simulationResults?.atom_data || fallbackMolecules[moleculeType] || fallbackMolecules.water;

  const atomsToXYZ = (atomList) => {
    if (!atomList || atomList.length === 0) {
      return '';
    }
    let xyz = `${atomList.length}\n`;
    xyz += 'Generated by Rwanda Quantum Agricultural Intelligence\n';
    atomList.forEach((atom) => {
      const symbol = atom.symbol || 'C';
      const x = typeof atom.x === 'number' ? atom.x.toFixed(4) : '0.0000';
      const y = typeof atom.y === 'number' ? atom.y.toFixed(4) : '0.0000';
      const z = typeof atom.z === 'number' ? atom.z.toFixed(4) : '0.0000';
      xyz += `${symbol} ${x} ${y} ${z}\n`;
    });
    return xyz;
  };

  useEffect(() => {
    try {
      const element = viewerRef.current;
      if (!element) return;

      if (!window.$3Dmol) {
        console.error('3Dmol.js not loaded');
        setError(true);
        return;
      }

      const viewer = window.$3Dmol.createViewer(element, {
        backgroundColor: '#000000'
      });

      const xyz = atomsToXYZ(atoms);
      if (!xyz) {
        viewer.clear();
        viewer.render();
        return;
      }

      viewer.addModel(xyz, 'xyz');
      viewer.setStyle({}, {
        stick: { radius: 0.2 },
        sphere: { scale: 0.3 }
      });

      // Enable hover labels for atoms
      viewer.setHoverable({}, true,
        function (atom) {
          if (!atom) return;
          atom.label = viewer.addLabel(atom.elem || 'Atom', {
            position: atom,
            backgroundColor: 'black',
            backgroundOpacity: 0.6,
            fontColor: 'white',
            fontSize: 12,
          });
        },
        function (atom) {
          if (atom && atom.label) {
            viewer.removeLabel(atom.label);
            delete atom.label;
          }
        }
      );

      if (simulationResults?.quantum_energy) {
        viewer.setBackgroundColor('#000022');
      }

      viewer.zoomTo();
      viewer.render();
    } catch (e) {
      console.error('Error initializing 3Dmol viewer', e);
      setError(true);
    }
  }, [atoms, simulationResults, moleculeType]);

  return (
    <div className="molecule-viewer">
      <div className="viewer-header">
        <h3>3D Molecular Visualization</h3>
        <div className="viewer-info">
          <span className={`status ${simulationResults ? 'active' : 'inactive'}`}>
            {simulationResults ? 'Quantum Active' : 'Classical View'}
          </span>
        </div>
      </div>
      
      <div className="canvas-container">
        {error ? (
          <div className="error-message">
            <p>3D visualization not supported. Please use a modern browser.</p>
          </div>
        ) : (
          <div
            ref={viewerRef}
            style={{ width: '100%', height: '100%' }}
          />
        )}
      </div>
      
      <div className="viewer-controls">
        <div className="control-instructions">
          <div className="instruction-item">
            <span className="instruction-label">Drag to rotate</span>
          </div>
          <div className="instruction-item">
            <span className="instruction-label">Scroll to zoom</span>
          </div>
          <div className="instruction-item">
            <span className="instruction-label">Right-click to pan</span>
          </div>
        </div>
      </div>
      
      {/* Simulation Results Section */}
      <div className="viewer-results">
        {simulationResults ? (
          <div className="results-summary">
            <h4>Simulation Results</h4>
            <div className="results-grid-viewer">
              <div className="result-item">
                <span className="result-label">Energy</span>
                <span className="result-value">
                  {simulationResults.classical_energy ? 
                    `${simulationResults.classical_energy.toFixed(3)} Ha` : 
                    simulationResults.quantum_energy ? 
                    `${simulationResults.quantum_energy.toFixed(3)} Ha` : 'N/A'}
                </span>
              </div>
              <div className="result-item">
                <span className="result-label">Dipole Moment</span>
                <span className="result-value">
                  {simulationResults.dipole_moment ? 
                    `${Math.sqrt(simulationResults.dipole_moment[0]**2 + simulationResults.dipole_moment[1]**2 + simulationResults.dipole_moment[2]**2).toFixed(3)} D` : 'N/A'}
                </span>
              </div>
              <div className="result-item">
                <span className="result-label">Agricultural Activity</span>
                <span className="result-value">
                  {simulationResults.agricultural_activity?.pesticide_activity_score ? 
                    `${(simulationResults.agricultural_activity.pesticide_activity_score * 100).toFixed(1)}%` : 'N/A'}
                </span>
              </div>
              <div className="result-item">
                <span className="result-label">Bioavailability</span>
                <span className="result-value">
                  {simulationResults.agricultural_activity?.bioavailability_prediction || 'Medium'}
                </span>
              </div>
              <div className="result-item">
                <span className="result-label">Safety Score</span>
                <span className="result-value">
                  {simulationResults.agricultural_activity?.safety_score ? 
                    `${(simulationResults.agricultural_activity.safety_score * 100).toFixed(0)}%` : 'High'}
                </span>
              </div>
              <div className="result-item">
                <span className="result-label">Computation Time</span>
                <span className="result-value">
                  {simulationResults.computation_time_ms ? `${simulationResults.computation_time_ms}ms` : '150ms'}
                </span>
              </div>
            </div>
          </div>
        ) : (
          <div className="no-simulation">
            <h4>No Simulation Data</h4>
            <p>Run a simulation to see molecular properties and agricultural metrics here.</p>
          </div>
        )}
      </div>
    </div>
  );
}

export default MoleculeViewer;