/* eslint-disable no-restricted-globals */
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Cache map tiles with Cache First strategy (fast loading, reduce bandwidth)
registerRoute(
    ({ url }) =>
        url.origin === 'https://server.arcgisonline.com' ||
        url.origin.includes('tile.openstreetmap.org') ||
        url.origin.includes('tile.opentopomap.org'),
    new CacheFirst({
        cacheName: 'map-tiles',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 500, // Cache up to 500 tiles
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
            }),
        ],
    })
);

// Cache district GeoJSON with Stale While Revalidate (balance speed and freshness)
registerRoute(
    ({ url }) => url.pathname.includes('/gis/districts'),
    new StaleWhileRevalidate({
        cacheName: 'district-data',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
            }),
        ],
    })
);

// Cache API responses with Network First (prefer fresh data, fallback to cache)
registerRoute(
    ({ url }) => url.origin === self.location.origin && url.pathname.startsWith('/api'),
    new NetworkFirst({
        cacheName: 'api-cache',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 24 * 60 * 60, // 1 day
            }),
        ],
    })
);

// Listen for messages from the client
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

// Log service worker activation
self.addEventListener('activate', (event) => {
    console.log('Service Worker activated');
});

console.log('Service Worker loaded');
